// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	v0 "github.com/zjzjzjzj1874/best-pracrice-go-zero/my_zero/internal/handler/v0"
	v0pro "github.com/zjzjzjzj1874/best-pracrice-go-zero/my_zero/internal/handler/v0/pro"
	v0test "github.com/zjzjzjzj1874/best-pracrice-go-zero/my_zero/internal/handler/v0/test"
	"github.com/zjzjzjzj1874/best-pracrice-go-zero/my_zero/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/liveness",
				Handler: livenessHandler(serverCtx),
			},
		},
		rest.WithPrefix("/go-zero"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/migrate",
				Handler: migrateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/go-zero"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: v0pro.RabbitmqProducerHandler(serverCtx),
			},
		},
		rest.WithPrefix("/go-zero/v0/pro"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{/*serverCtx.FlowLimit*/},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: v0test.PostHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: v0test.GetHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/excel",
					Handler: v0test.ExcelParseHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/go-zero/v0/test"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{/*serverCtx.FlowLimit,*/ serverCtx.LogTrace},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/manual",
					Handler: v0.ManualRunTaskHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/go-zero/v0/test"),
	)
}
