// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	v0pro "github.com/zjzjzjzj1874/best-pracrice-go-zero/my_zero/internal/handler/v0/pro"
	"github.com/zjzjzjzj1874/best-pracrice-go-zero/my_zero/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/liveness",
				Handler: livenessHandler(serverCtx),
			},
		},
		rest.WithPrefix("/go-zero"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: v0pro.RabbitMQProducerHandler(serverCtx),
			},
		},
		rest.WithPrefix("/go-zero/v0/pro"),
	)
}
