// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/zjzjzjzj1874/best-pracrice-go-zero/my_zero/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/liveness",
				Handler: livenessHandler(serverCtx),
			},
		},
		rest.WithPrefix("/go-zero"),
	)
}
