version: '3.0'

services:
  my-zero:
    env_file: # 这个是默认的,不写也是这个
      - .env
    build:
      context: . # build上下文地址
      dockerfile: ./my_zero/Dockerfile # 使用的dockerfile构建文件
      cache_from: # 使用缓存加速构建速度
        - zero:base
        - type=local,src=path/to/cache
        - type=gha
    image: my-zero:${Tag}
    container_name: my-zero
    restart: always
    command: ./my-zero -f /app/etc/my-zero.${Env}.yaml
    privileged: true
    volumes:
      - ${ProjectPath}/my_zero/etc:/app/etc
    ports:
      - "80:8888"
      - "10010:10010" # 普罗米修斯接口