// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	task "github.com/zjzjzjzj1874/best-pracrice-go-zero/task/internal/handler/task"
	"github.com/zjzjzjzj1874/best-pracrice-go-zero/task/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/liveness",
				Handler: task.LivenessHandler(serverCtx),
			},
		},
		rest.WithPrefix("/task"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/swagger",
				Handler: task.SwaggerHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/swagger-bin",
				Handler: task.SwaggerGetHandler(serverCtx),
			},
		},
		rest.WithPrefix("/task"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/manual",
				Handler: task.ManualRunTaskHandler(serverCtx),
			},
		},
		rest.WithPrefix("/task/v0"),
	)
}
