// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	bulk "github.com/zjzjzjzj1874/best-pracrice-go-zero/task/internal/handler/bulk"
	imp "github.com/zjzjzjzj1874/best-pracrice-go-zero/task/internal/handler/imp"
	task "github.com/zjzjzjzj1874/best-pracrice-go-zero/task/internal/handler/task"
	"github.com/zjzjzjzj1874/best-pracrice-go-zero/task/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/liveness",
				Handler: task.LivenessHandler(serverCtx),
			},
		},
		rest.WithPrefix("/task"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/swagger",
				Handler: task.SwaggerHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/swagger-bin",
				Handler: task.SwaggerGetHandler(serverCtx),
			},
		},
		rest.WithPrefix("/task"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.LogTrace},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/run/:name",
					Handler: task.ManualRunHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/task/v0"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.LogTrace},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/:id",
					Handler: imp.ImportHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/task/import"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.LogTrace},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: bulk.BulkHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/task/bulk"),
	)
}
