// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	customer "github.com/zjzjzjzj1874/best-pracrice-go-zero/user/api/internal/handler/customer"
	liveness "github.com/zjzjzjzj1874/best-pracrice-go-zero/user/api/internal/handler/liveness"
	swagger "github.com/zjzjzjzj1874/best-pracrice-go-zero/user/api/internal/handler/swagger"
	"github.com/zjzjzjzj1874/best-pracrice-go-zero/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/liveness",
				Handler: liveness.LivenessHandler(serverCtx),
			},
		},
		rest.WithPrefix("/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/swagger",
				Handler: swagger.SwaggerHandler(serverCtx),
			},
		},
		rest.WithPrefix("/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Recover, serverCtx.Log},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/login-phone",
					Handler: customer.LoginPhoneHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/login-wechat",
					Handler: customer.LoginWechatHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/customers"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Recover, serverCtx.Log, serverCtx.FlowLimit},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/get-phone-auth",
					Handler: customer.GetCellPhoneAuthHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/customers"),
	)
}
