// Code generated by goctl. DO NOT EDIT.
package types

type GetCellPhoneAuthReq struct {
	Phone string `json:"phone" description:"客户电话"`
}

type GetCellPhoneAuthResp struct {
	Code int32  `json:"code,default=200" description:"返回码"`
	Msg  string `json:"msg,default=请求成功" description:"消息说明"`
}

type LoginData struct {
	Token string `json:"token" description:"jwt"`
	Extra string `json:"extra" description:"额外信息"`
}

type LoginPhoneReq struct {
	Phone              string `json:"phone" description:"手机号"`
	PhoneAuth          string `json:"phone_auth" description:"手机验证码"`
	BrowserFingerprint string `json:"browser_fingerprint" description:"浏览器指纹"`
}

type LoginPhoneResp struct {
	Code int32      `json:"code,default=200" description:"返回码"`
	Msg  string     `json:"msg,default=请求成功" description:"消息说明"`
	Data *LoginData `json:"data" description:"登录数据"`
}

type LoginWechatReq struct {
	Code               string `json:"code" description:"登录Code"`
	BrowserFingerprint string `json:"browser_fingerprint" description:"浏览器指纹"`
}

type LoginWechatResp struct {
	Code int32      `json:"code,default=200" description:"返回码"`
	Msg  string     `json:"msg,default=请求成功" description:"消息说明"`
	Data *LoginData `json:"data" description:"登录数据"`
}
