// Code generated by goctl. DO NOT EDIT.
package types

type OrderReq struct {
	Id int64 `path:"id"`
}

type OrderReply struct {
	Id    int64  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
