// Code generated by goctl. DO NOT EDIT.
package types

type LivenessResponse struct {
	Msg string `json:"msg" description:"msg"`
}

type Request struct {
}

type Response struct {
}

type ManualExecTaskRequest struct {
	Name string `json:"name" description:"表达式任务名称"` // 任务名称
}

type ManualExecTaskResponse struct {
	Msg string `json:"msg" description:"信息"`
}
