// Code generated by goctl. DO NOT EDIT.
package types

type LivenessResponse struct {
	Msg string `json:"msg" description:"msg"`
}

type Request struct {
}

type Response struct {
}

type ManualRunReq struct {
	Name string `path:"name" description:"任务名称"`
}

type ManualRunResp struct {
	Msg string `json:"msg" description:"信息"`
}

type ImportReq struct {
	Id             string `path:"id" description:"objectId" validate:"required"`
	BlackWhiteType int    `form:"black_white_type" description:"黑白名单类型 1黑 2白" validate:"required"`
}

type ImportResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
	Data string `json:"data"`
}
