// Code generated by goctl. DO NOT EDIT.
package types

type LivenessRequest struct {
}

type LivenessResponse struct {
}

type MigrateRequest struct {
	TableNames []string `json:"table_names,omitempty" description:"更新表名列表"`
}

type MigrateResponse struct {
}

type RabbitmqProRequest struct {
	Name    string   `json:"name"`    // 姓名
	Age     int      `json:"age"`     // 年龄
	Hobbies []string `json:"hobbies"` // 爱好
}

type RabbitmqProResponse struct {
}

type ListReq struct {
	CreatedTime []string `json:"created_time,optional" description:"入库时间"`
	ID          string   `json:"id,optional" description:"内容id"`
	Name        string   `json:"name,optional" description:"名称"`
}

type Response struct {
}
