// Code generated by goctl. DO NOT EDIT.
package types

type LivenessRequest struct {
}

type LivenessResponse struct {
}

type MigrateRequest struct {
	TableNames []string `json:"table_names,omitempty" description:"更新表名列表"`
}

type MigrateResponse struct {
}

type RabbitmqProRequest struct {
	Name    string   `json:"name"`    // 姓名
	Age     int      `json:"age"`     // 年龄
	Hobbies []string `json:"hobbies"` // 爱好
}

type RabbitmqProResponse struct {
}

type ListReq struct {
	CreatedTime []string `json:"created_time,optional" description:"入库时间"`
	ID          string   `json:"id,optional" description:"内容id"`
	Name        string   `json:"name,optional" validate:"min=3,max=10" description:"名称"`
}

type Response struct {
}

type MongoTest struct {
	ID        string   `bson:"_id" json:"id" description:"主键ID"`
	TestName  string   `bson:"test_name" json:"test_name" description:"测试名称"`
	CreatedAt int64    `bson:"created_at" json:"created_at" description:"创建时间"`
	Hobbies   []string `bson:"hobbies" json:"hobbies" description:"爱好"`
}

type ManualExecTaskRequest struct {
	Name string `json:"name" description:"表达式任务名称"`
}

type ManualExecTaskResponse struct {
	Msg string `json:"msg" description:"返回信息"`
}
