// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/zjzjzjzj1874/best-pracrice-go-zero/tests/gorm/dal/model"
)

func newTUser(db *gorm.DB) tUser {
	_tUser := tUser{}

	_tUser.tUserDo.UseDB(db)
	_tUser.tUserDo.UseModel(&model.TUser{})

	tableName := _tUser.tUserDo.TableName()
	_tUser.ALL = field.NewField(tableName, "*")
	_tUser.ID = field.NewInt64(tableName, "id")
	_tUser.CreatedAt = field.NewTime(tableName, "created_at")
	_tUser.UpdatedAt = field.NewTime(tableName, "updated_at")
	_tUser.DeletedAt = field.NewField(tableName, "deleted_at")
	_tUser.Name = field.NewString(tableName, "name")
	_tUser.Email = field.NewString(tableName, "email")
	_tUser.NickName = field.NewString(tableName, "nick_name")
	_tUser.Age = field.NewInt32(tableName, "age")
	_tUser.Phone = field.NewString(tableName, "phone")

	_tUser.fillFieldMap()

	return _tUser
}

type tUser struct {
	tUserDo tUserDo

	ALL       field.Field
	ID        field.Int64
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	Name      field.String
	Email     field.String
	NickName  field.String
	Age       field.Int32
	Phone     field.String

	fieldMap map[string]field.Expr
}

func (t tUser) Table(newTableName string) *tUser {
	t.tUserDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tUser) As(alias string) *tUser {
	t.tUserDo.DO = *(t.tUserDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tUser) updateTableName(table string) *tUser {
	t.ALL = field.NewField(table, "*")
	t.ID = field.NewInt64(table, "id")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.DeletedAt = field.NewField(table, "deleted_at")
	t.Name = field.NewString(table, "name")
	t.Email = field.NewString(table, "email")
	t.NickName = field.NewString(table, "nick_name")
	t.Age = field.NewInt32(table, "age")
	t.Phone = field.NewString(table, "phone")

	t.fillFieldMap()

	return t
}

func (t *tUser) WithContext(ctx context.Context) *tUserDo { return t.tUserDo.WithContext(ctx) }

func (t tUser) TableName() string { return t.tUserDo.TableName() }

func (t tUser) Alias() string { return t.tUserDo.Alias() }

func (t *tUser) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tUser) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 9)
	t.fieldMap["id"] = t.ID
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["deleted_at"] = t.DeletedAt
	t.fieldMap["name"] = t.Name
	t.fieldMap["email"] = t.Email
	t.fieldMap["nick_name"] = t.NickName
	t.fieldMap["age"] = t.Age
	t.fieldMap["phone"] = t.Phone
}

func (t tUser) clone(db *gorm.DB) tUser {
	t.tUserDo.ReplaceDB(db)
	return t
}

type tUserDo struct{ gen.DO }

func (t tUserDo) Debug() *tUserDo {
	return t.withDO(t.DO.Debug())
}

func (t tUserDo) WithContext(ctx context.Context) *tUserDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tUserDo) ReadDB() *tUserDo {
	return t.Clauses(dbresolver.Read)
}

func (t tUserDo) WriteDB() *tUserDo {
	return t.Clauses(dbresolver.Write)
}

func (t tUserDo) Clauses(conds ...clause.Expression) *tUserDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tUserDo) Returning(value interface{}, columns ...string) *tUserDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tUserDo) Not(conds ...gen.Condition) *tUserDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tUserDo) Or(conds ...gen.Condition) *tUserDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tUserDo) Select(conds ...field.Expr) *tUserDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tUserDo) Where(conds ...gen.Condition) *tUserDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tUserDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *tUserDo {
	return t.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (t tUserDo) Order(conds ...field.Expr) *tUserDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tUserDo) Distinct(cols ...field.Expr) *tUserDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tUserDo) Omit(cols ...field.Expr) *tUserDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tUserDo) Join(table schema.Tabler, on ...field.Expr) *tUserDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tUserDo) LeftJoin(table schema.Tabler, on ...field.Expr) *tUserDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tUserDo) RightJoin(table schema.Tabler, on ...field.Expr) *tUserDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tUserDo) Group(cols ...field.Expr) *tUserDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tUserDo) Having(conds ...gen.Condition) *tUserDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tUserDo) Limit(limit int) *tUserDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tUserDo) Offset(offset int) *tUserDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tUserDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *tUserDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tUserDo) Unscoped() *tUserDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tUserDo) Create(values ...*model.TUser) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tUserDo) CreateInBatches(values []*model.TUser, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tUserDo) Save(values ...*model.TUser) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tUserDo) First() (*model.TUser, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TUser), nil
	}
}

func (t tUserDo) Take() (*model.TUser, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TUser), nil
	}
}

func (t tUserDo) Last() (*model.TUser, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TUser), nil
	}
}

func (t tUserDo) Find() ([]*model.TUser, error) {
	result, err := t.DO.Find()
	return result.([]*model.TUser), err
}

func (t tUserDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TUser, err error) {
	buf := make([]*model.TUser, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tUserDo) FindInBatches(result *[]*model.TUser, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tUserDo) Attrs(attrs ...field.AssignExpr) *tUserDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tUserDo) Assign(attrs ...field.AssignExpr) *tUserDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tUserDo) Joins(fields ...field.RelationField) *tUserDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tUserDo) Preload(fields ...field.RelationField) *tUserDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tUserDo) FirstOrInit() (*model.TUser, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TUser), nil
	}
}

func (t tUserDo) FirstOrCreate() (*model.TUser, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TUser), nil
	}
}

func (t tUserDo) FindByPage(offset int, limit int) (result []*model.TUser, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tUserDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tUserDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t *tUserDo) withDO(do gen.Dao) *tUserDo {
	t.DO = *do.(*gen.DO)
	return t
}
