// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTScanaContent = "t_scana_content"

// TScanaContent mapped from table <t_scana_content>
type TScanaContent struct {
	ID                      int32     `gorm:"column:id;primaryKey" json:"id"`
	BatchID                 string    `gorm:"column:batch_id;not null" json:"batch_id"` // 批次号
	UpdateTime              time.Time `gorm:"column:update_time" json:"update_time"`
	FirstAuditReceiveTime   time.Time `gorm:"column:first_audit_receive_time" json:"first_audit_receive_time"` // 初审领单时间
	FirstAuditTime          time.Time `gorm:"column:first_audit_time" json:"first_audit_time"`                 // 初审时间
	InTime                  time.Time `gorm:"column:in_time;not null" json:"in_time"`                          // 客户入单时间
	FinalResultTime         time.Time `gorm:"column:final_result_time;not null" json:"final_result_time"`      // 最终审核时间,最后一次审核更新
	RecheckAuditReceiveTime time.Time `gorm:"column:recheck_audit_receive_time" json:"recheck_audit_receive_time"`
	TimeoutDuration         time.Time `gorm:"column:timeout_duration" json:"timeout_duration"`
	CallbackTime            time.Time `gorm:"column:callback_time" json:"callback_time"`
}

// TableName TScanaContent's table name
func (*TScanaContent) TableName() string {
	return TableNameTScanaContent
}
