// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	v0order "github.com/zjzjzjzj1874/best-pracrice-go-zero/order/api/internal/handler/v0/order"
	"github.com/zjzjzjzj1874/best-pracrice-go-zero/order/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/order/:id",
				Handler: v0order.GetOrderHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v0/api"),
	)
}
