// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTMock = "t_mock"

// TMock mapped from table <t_mock>
type TMock struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	TestName  string         `gorm:"column:test_name" json:"test_name"`
	Hobbies   string         `gorm:"column:hobbies" json:"hobbies"`     // 爱好
	SLATimes  string         `gorm:"column:sla_times" json:"sla_times"` // 对象测试字段
}

// TableName TMock's table name
func (*TMock) TableName() string {
	return TableNameTMock
}
