// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTTest = "t_test"

// TTest mapped from table <t_test>
type TTest struct {
	ID           int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt    time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	ReceiveTime  time.Time      `gorm:"column:receive_time" json:"receive_time"` // 收货时间
	UpdateTime   time.Time      `gorm:"column:update_time;not null" json:"update_time"`
	CallbackTime time.Time      `gorm:"column:callback_time" json:"callback_time"` // 回调时间
	TestTime     time.Time      `gorm:"column:test_time" json:"test_time"`         // 测试时间
	TestName     string         `gorm:"column:test_name" json:"test_name"`         // 测试名称
	TestTime1    time.Time      `gorm:"column:test_time1" json:"test_time1"`       // 测试时间1
	Emotion      string         `gorm:"column:emotion" json:"emotion"`             // 表情
}

// TableName TTest's table name
func (*TTest) TableName() string {
	return TableNameTTest
}
