// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
)

func Use(db *gorm.DB) *Query {
	return &Query{
		db:            db,
		TMock:         newTMock(db),
		TScanaContent: newTScanaContent(db),
		TTest:         newTTest(db),
		TUser:         newTUser(db),
	}
}

type Query struct {
	db *gorm.DB

	TMock         tMock
	TScanaContent tScanaContent
	TTest         tTest
	TUser         tUser
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:            db,
		TMock:         q.TMock.clone(db),
		TScanaContent: q.TScanaContent.clone(db),
		TTest:         q.TTest.clone(db),
		TUser:         q.TUser.clone(db),
	}
}

type queryCtx struct {
	TMock         *tMockDo
	TScanaContent *tScanaContentDo
	TTest         *tTestDo
	TUser         *tUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		TMock:         q.TMock.WithContext(ctx),
		TScanaContent: q.TScanaContent.WithContext(ctx),
		TTest:         q.TTest.WithContext(ctx),
		TUser:         q.TUser.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	return &QueryTx{q.clone(q.db.Begin(opts...))}
}

type QueryTx struct{ *Query }

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
